export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_USER = 'AUTH_USER';
export const ADD_TO_CART_USER = 'ADD_TO_CART_USER';
export const GET_CART_ITEMS_USER = 'GET_CART_ITEMS_USER';
export const REMOVE_CART_ITEM_USER = 'REMOVE_CART_ITEM_USER';